INFO 2020-08-10 10:22:30,716 autoreload 820 4466294208 Watching for file changes with StatReloader
INFO 2020-08-10 10:22:47,918 autoreload 892 4555636160 Watching for file changes with StatReloader
INFO 2020-08-10 10:22:54,853 basehttp 892 123145482276864 "GET /static/css/main.css HTTP/1.1" 200 7282
INFO 2020-08-10 10:22:54,879 basehttp 892 123145499066368 "GET /static/js/jquery-1.8.3.min.js HTTP/1.1" 200 93636
INFO 2020-08-10 10:22:54,891 basehttp 892 123145515855872 "GET /static/js/station_map.js HTTP/1.1" 200 57047
INFO 2020-08-10 10:22:54,901 basehttp 892 123145465487360 "GET / HTTP/1.1" 200 936653
INFO 2020-08-10 10:22:54,906 basehttp 892 123145532645376 "GET /static/js/jquery-ui-timepicker-addon.min.js HTTP/1.1" 200 41441
INFO 2020-08-10 10:22:54,955 basehttp 892 123145549434880 "GET /static/css/jquery-ui-timepicker-addon.min.css HTTP/1.1" 304 0
INFO 2020-08-10 10:22:54,960 basehttp 892 123145482276864 "GET /static/js/cookiemonster.js HTTP/1.1" 304 0
INFO 2020-08-10 10:23:03,593 basehttp 892 123145465487360 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 10:23:03,914 basehttp 892 123145532645376 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 10:23:13,065 basehttp 892 123145532645376 "GET / HTTP/1.1" 200 936653
INFO 2020-08-10 10:23:14,751 basehttp 892 123145465487360 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 10:23:14,802 basehttp 892 123145532645376 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 10:23:15,076 basehttp 892 123145532645376 "GET /static/images/favicon.png HTTP/1.1" 200 40821
INFO 2020-08-10 10:23:34,399 basehttp 892 123145465487360 "GET / HTTP/1.1" 200 936653
INFO 2020-08-10 10:23:34,442 basehttp 892 123145465487360 "GET /static/css/main.css HTTP/1.1" 200 7282
INFO 2020-08-10 10:23:34,444 basehttp 892 123145482276864 "GET /static/js/jquery-1.8.3.min.js HTTP/1.1" 200 93636
INFO 2020-08-10 10:23:34,454 basehttp 892 123145482276864 "GET /static/js/station_map.js HTTP/1.1" 200 57047
INFO 2020-08-10 10:23:34,473 basehttp 892 123145482276864 "GET /static/js/cookiemonster.js HTTP/1.1" 200 2761
INFO 2020-08-10 10:23:34,474 basehttp 892 123145499066368 "GET /static/css/jquery-ui-timepicker-addon.min.css HTTP/1.1" 200 1901
INFO 2020-08-10 10:23:34,475 basehttp 892 123145465487360 "GET /static/js/jquery-ui-timepicker-addon.min.js HTTP/1.1" 200 41441
INFO 2020-08-10 10:23:37,143 basehttp 892 123145499066368 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 10:23:37,216 basehttp 892 123145465487360 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 10:23:37,530 basehttp 892 123145465487360 "GET /static/images/favicon.png HTTP/1.1" 200 40821
INFO 2020-08-10 10:23:49,597 basehttp 892 123145465487360 "POST /app01/stop/ HTTP/1.1" 200 671
INFO 2020-08-10 10:23:55,001 basehttp 892 123145465487360 "POST /app01/stop/ HTTP/1.1" 200 3499
INFO 2020-08-10 10:24:09,985 basehttp 892 123145465487360 "POST /app01/stop/ HTTP/1.1" 200 1241
INFO 2020-08-10 10:24:16,581 basehttp 892 123145465487360 "POST /app01/stop/ HTTP/1.1" 200 1256
INFO 2020-08-10 10:39:01,208 autoreload 964 4522700224 Watching for file changes with StatReloader
INFO 2020-08-10 10:39:07,432 basehttp 964 123145440092160 "GET / HTTP/1.1" 200 936653
INFO 2020-08-10 10:39:15,174 basehttp 964 123145456881664 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 10:39:15,328 basehttp 964 123145440092160 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 10:39:24,849 basehttp 964 123145440092160 "POST /app01/stop/ HTTP/1.1" 200 671
INFO 2020-08-10 11:56:57,301 autoreload 1377 4642389440 Watching for file changes with StatReloader
INFO 2020-08-10 11:57:04,075 basehttp 1377 123145454030848 "GET / HTTP/1.1" 200 936653
INFO 2020-08-10 11:57:08,977 basehttp 1377 123145470820352 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 11:57:09,153 basehttp 1377 123145454030848 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 11:57:24,313 basehttp 1377 123145454030848 "POST /app01/stop/ HTTP/1.1" 200 703
INFO 2020-08-10 13:27:49,718 autoreload 2645 4688637376 Watching for file changes with StatReloader
INFO 2020-08-10 13:27:54,960 basehttp 2645 123145518280704 "GET / HTTP/1.1" 200 936705
INFO 2020-08-10 13:28:00,060 basehttp 2645 123145535070208 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 13:28:00,310 basehttp 2645 123145518280704 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 13:28:15,393 basehttp 2645 123145518280704 "POST /app01/leapcard/ HTTP/1.1" 200 143
INFO 2020-08-10 13:33:44,494 autoreload 2772 4612443584 Watching for file changes with StatReloader
INFO 2020-08-10 13:34:23,904 autoreload 2772 4612443584 /Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/dublinbus/urls.py changed, reloading.
INFO 2020-08-10 13:34:25,279 autoreload 2810 4364971456 Watching for file changes with StatReloader
INFO 2020-08-10 13:34:31,115 autoreload 2810 4364971456 /Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/dublinbus/urls.py changed, reloading.
INFO 2020-08-10 13:34:31,685 autoreload 2823 4475211200 Watching for file changes with StatReloader
INFO 2020-08-10 13:34:40,913 autoreload 2823 4475211200 /Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/dublinbus/urls.py changed, reloading.
INFO 2020-08-10 13:34:41,703 autoreload 2835 4648312256 Watching for file changes with StatReloader
INFO 2020-08-10 13:34:49,268 basehttp 2835 123145454002176 "GET / HTTP/1.1" 200 936699
INFO 2020-08-10 13:34:49,398 basehttp 2835 123145504370688 "GET /static/js/cookiemonster.js HTTP/1.1" 200 2761
INFO 2020-08-10 13:34:49,399 basehttp 2835 123145537949696 "GET /static/css/jquery-ui-timepicker-addon.min.css HTTP/1.1" 200 1901
INFO 2020-08-10 13:34:49,402 basehttp 2835 123145487581184 "GET /static/js/station_map.js HTTP/1.1" 200 57047
INFO 2020-08-10 13:34:49,403 basehttp 2835 123145521160192 "GET /static/js/jquery-ui-timepicker-addon.min.js HTTP/1.1" 200 41441
INFO 2020-08-10 13:34:49,405 basehttp 2835 123145470791680 "GET /static/js/jquery-1.8.3.min.js HTTP/1.1" 200 93636
INFO 2020-08-10 13:34:49,408 basehttp 2835 123145454002176 "GET /static/css/main.css HTTP/1.1" 200 7282
INFO 2020-08-10 13:34:57,962 basehttp 2835 123145470791680 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 13:34:58,051 basehttp 2835 123145454002176 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 13:35:00,922 basehttp 2835 123145454002176 "POST /leapcard/ HTTP/1.1" 200 18
INFO 2020-08-10 15:08:20,040 autoreload 3313 4578495936 Watching for file changes with StatReloader
INFO 2020-08-10 15:08:24,837 basehttp 3313 123145342230528 "GET / HTTP/1.1" 200 936696
INFO 2020-08-10 15:08:30,207 basehttp 3313 123145359020032 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 15:08:30,466 basehttp 3313 123145342230528 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 15:08:33,211 basehttp 3313 123145342230528 "POST /leapcard/ HTTP/1.1" 200 18
INFO 2020-08-10 15:11:11,344 autoreload 3397 4644142528 Watching for file changes with StatReloader
INFO 2020-08-10 15:12:52,124 autoreload 3446 4442668480 Watching for file changes with StatReloader
INFO 2020-08-10 15:13:23,628 autoreload 3488 4765445568 Watching for file changes with StatReloader
INFO 2020-08-10 15:13:58,548 autoreload 3524 4549541312 Watching for file changes with StatReloader
INFO 2020-08-10 15:14:26,016 autoreload 3554 4562513344 Watching for file changes with StatReloader
INFO 2020-08-10 15:15:37,296 autoreload 3554 4562513344 /Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/dublinbus/urls.py changed, reloading.
INFO 2020-08-10 15:15:38,690 autoreload 3567 4706041280 Watching for file changes with StatReloader
INFO 2020-08-10 15:15:40,871 autoreload 3587 4597456320 Watching for file changes with StatReloader
INFO 2020-08-10 15:15:51,234 autoreload 3587 4597456320 /Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/dublinbus/urls.py changed, reloading.
INFO 2020-08-10 15:15:51,819 autoreload 3603 4315872704 Watching for file changes with StatReloader
INFO 2020-08-10 15:15:55,943 autoreload 3623 4561251776 Watching for file changes with StatReloader
INFO 2020-08-10 15:16:06,029 basehttp 3623 123145556819968 "GET / HTTP/1.1" 200 936699
INFO 2020-08-10 15:16:11,239 basehttp 3623 123145573609472 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 15:16:11,427 basehttp 3623 123145556819968 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 15:16:14,508 basehttp 3623 123145556819968 "POST /leapcard/ HTTP/1.1" 200 18
INFO 2020-08-10 15:17:46,450 autoreload 3728 4570246592 Watching for file changes with StatReloader
INFO 2020-08-10 15:17:51,290 basehttp 3728 123145411960832 "GET / HTTP/1.1" 200 936699
INFO 2020-08-10 15:17:53,100 basehttp 3728 123145428750336 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 15:17:53,227 basehttp 3728 123145411960832 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 15:18:00,876 basehttp 3728 123145411960832 "POST /leapcard/ HTTP/1.1" 200 18
INFO 2020-08-10 15:25:48,364 autoreload 3892 4499918272 Watching for file changes with StatReloader
INFO 2020-08-10 15:25:53,284 basehttp 3892 123145357660160 "GET / HTTP/1.1" 200 936756
INFO 2020-08-10 15:25:58,052 basehttp 3892 123145374449664 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 15:25:58,186 basehttp 3892 123145357660160 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 15:25:59,219 basehttp 3892 123145357660160 "GET /zzz HTTP/1.1" 200 2
WARNING 2020-08-10 15:25:59,302 log 3892 123145357660160 Not Found: /favicon.ico
WARNING 2020-08-10 15:25:59,303 basehttp 3892 123145357660160 "GET /favicon.ico HTTP/1.1" 404 3877
INFO 2020-08-10 15:26:01,642 basehttp 3892 123145374449664 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 15:26:01,705 basehttp 3892 123145357660160 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 15:28:52,047 autoreload 4021 4524690880 Watching for file changes with StatReloader
INFO 2020-08-10 15:28:55,490 basehttp 4021 123145361006592 "GET / HTTP/1.1" 200 936746
INFO 2020-08-10 15:28:56,986 basehttp 4021 123145361006592 "GET /static/images/favicon.png HTTP/1.1" 200 40821
INFO 2020-08-10 15:29:05,561 basehttp 4021 123145377796096 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 15:29:05,643 basehttp 4021 123145361006592 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 15:29:07,194 basehttp 4021 123145361006592 "GET / HTTP/1.1" 200 936751
INFO 2020-08-10 15:29:07,766 basehttp 4021 123145377796096 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 15:29:07,837 basehttp 4021 123145361006592 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 15:29:08,042 basehttp 4021 123145361006592 "GET /static/images/favicon.png HTTP/1.1" 200 40821
INFO 2020-08-10 15:29:16,754 basehttp 4021 123145361006592 "GET / HTTP/1.1" 200 936756
INFO 2020-08-10 15:29:17,391 basehttp 4021 123145377796096 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 15:29:17,446 basehttp 4021 123145361006592 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 15:29:17,587 basehttp 4021 123145361006592 "GET /static/images/favicon.png HTTP/1.1" 200 40821
INFO 2020-08-10 15:29:19,865 basehttp 4021 123145361006592 "GET /zzz HTTP/1.1" 200 2
INFO 2020-08-10 15:34:27,219 autoreload 4242 4444085696 Watching for file changes with StatReloader
INFO 2020-08-10 15:36:34,884 autoreload 4319 4668394944 Watching for file changes with StatReloader
ERROR 2020-08-10 15:36:39,037 log 4319 123145593913344 Internal Server Error: /
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'app01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/app01/views.py", line 46, in index
    return render(request,'index.html', context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app01' is not a registered namespace
ERROR 2020-08-10 15:36:39,948 basehttp 4319 123145593913344 "GET / HTTP/1.1" 500 201366
ERROR 2020-08-10 15:37:13,752 log 4319 123145593913344 Internal Server Error: /
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'app01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/app01/views.py", line 46, in index
    return render(request,'index.html', context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app01' is not a registered namespace
ERROR 2020-08-10 15:37:14,172 basehttp 4319 123145593913344 "GET / HTTP/1.1" 500 201407
ERROR 2020-08-10 15:37:32,270 log 4319 123145593913344 Internal Server Error: /
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'app01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/app01/views.py", line 46, in index
    return render(request,'index.html', context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app01' is not a registered namespace
ERROR 2020-08-10 15:37:32,699 basehttp 4319 123145593913344 "GET / HTTP/1.1" 500 201407
ERROR 2020-08-10 15:37:42,520 log 4319 123145593913344 Internal Server Error: /
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/urls/base.py", line 72, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'app01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/app01/views.py", line 46, in index
    return render(request,'index.html', context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/urls/base.py", line 83, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'app01' is not a registered namespace
ERROR 2020-08-10 15:37:42,937 basehttp 4319 123145593913344 "GET / HTTP/1.1" 500 198358
INFO 2020-08-10 15:37:55,561 basehttp 4319 123145593913344 "GET / HTTP/1.1" 200 936709
INFO 2020-08-10 15:37:55,596 basehttp 4319 123145610702848 "GET /static/css/main.css HTTP/1.1" 200 7282
INFO 2020-08-10 15:37:55,629 basehttp 4319 123145627492352 "GET /static/js/cookiemonster.js HTTP/1.1" 200 2761
INFO 2020-08-10 15:37:55,630 basehttp 4319 123145661071360 "GET /static/css/jquery-ui-timepicker-addon.min.css HTTP/1.1" 200 1901
INFO 2020-08-10 15:37:55,631 basehttp 4319 123145610702848 "GET /static/js/station_map.js HTTP/1.1" 200 57047
INFO 2020-08-10 15:37:55,634 basehttp 4319 123145593913344 "GET /static/js/jquery-1.8.3.min.js HTTP/1.1" 200 93636
INFO 2020-08-10 15:37:55,635 basehttp 4319 123145644281856 "GET /static/js/jquery-ui-timepicker-addon.min.js HTTP/1.1" 200 41441
INFO 2020-08-10 15:37:58,420 basehttp 4319 123145644281856 "GET /static/images/favicon.png HTTP/1.1" 200 40821
ERROR 2020-08-10 15:54:48,995 log 4798 4673588672 Internal Server Error: /leapcard/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view app01.views.leapcard didn't return an HttpResponse object. It returned None instead.
ERROR 2020-08-10 15:56:54,307 log 4837 4675550656 Internal Server Error: /leapcard/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view app01.views.leapcard didn't return an HttpResponse object. It returned None instead.
ERROR 2020-08-10 15:57:04,877 log 4869 4442955200 Internal Server Error: /leapcard/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view app01.views.leapcard didn't return an HttpResponse object. It returned None instead.
ERROR 2020-08-10 15:58:39,325 log 4950 4548599232 Internal Server Error: /leapcard/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view app01.views.leapcard didn't return an HttpResponse object. It returned None instead.
ERROR 2020-08-10 15:59:20,080 log 5025 4553608640 Internal Server Error: /leapcard/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/app01/views.py", line 65, in leapcard
    username = request.POST['username']
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
ERROR 2020-08-10 16:00:54,577 log 5065 4593470912 Internal Server Error: /leapcard/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view app01.views.leapcard didn't return an HttpResponse object. It returned None instead.
ERROR 2020-08-10 16:07:43,919 log 5301 4539678144 Internal Server Error: /leapcard/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/app01/views.py", line 90, in leapcard
    return render(request,'index.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
INFO 2020-08-10 16:08:22,134 autoreload 5403 4462476736 Watching for file changes with StatReloader
INFO 2020-08-10 16:08:26,845 basehttp 5403 123145562791936 "GET / HTTP/1.1" 200 936709
INFO 2020-08-10 16:08:32,080 basehttp 5403 123145579581440 "POST /app01//weather HTTP/1.1" 200 93
INFO 2020-08-10 16:08:32,287 basehttp 5403 123145562791936 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 16:08:38,024 basehttp 5403 123145562791936 "POST /leapcard/ HTTP/1.1" 200 18
INFO 2020-08-10 16:11:50,598 autoreload 5468 4646690240 Watching for file changes with StatReloader
ERROR 2020-08-10 16:26:56,293 log 5790 4559519168 Internal Server Error: /leapcard/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jobs/Desktop/dublin-bus-rtpi/dublinbus/app01/views.py", line 65, in leapcard
    username = request.POST['username']
  File "/opt/anaconda3/envs/group2/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
INFO 2020-08-10 16:42:52,022 autoreload 6103 4582538688 Watching for file changes with StatReloader
INFO 2020-08-10 16:42:57,150 basehttp 6103 123145576370176 "GET / HTTP/1.1" 200 936709
INFO 2020-08-10 16:43:02,552 basehttp 6103 123145593159680 "POST /app01//weather HTTP/1.1" 200 95
INFO 2020-08-10 16:43:02,685 basehttp 6103 123145576370176 "POST /app01//init HTTP/1.1" 200 89
INFO 2020-08-10 16:44:49,845 autoreload 6175 4413730240 Watching for file changes with StatReloader
